version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.2.0
