language: node_js

node_js:
  - "14"
  - "12"
  - "11"
  - "10"
install:
  - npm ci

script:
  - npm run lint:ci
  - npm run test:cov

notifications:
  email:
    on_success: never
    on_failure: always