language: node_js

node_js:
  - "15"
  - "14"
  - "12"
  - "10"
install:
  - npm i

script:
  - npm run lint:ci
  - npm run test:cov

notifications:
  email:
    on_success: never
    on_failure: always