# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor: node/default
    resource_class: small
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-npm: true
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Lint
          command: npm run lint:ci
      - run:
          name: Run Build
          command: npm run build
      - run:
          name: Run Tests
          command: npm run test:cov
      - run:
          name: Upload Coveralls Data
          command: npm run report
          when: always # Uploads code coverage results, pass or fail

workflows:
  orb-free-workflow:
    jobs:
      - test:
          matrix:
            parameters:
              node-version: ['16.4', '14.17', '12.22']